/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.*;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author TIMOON
 */
public class DN extends javax.swing.JFrame {

    Border red_bottom_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red);
    /**
     * Creates new form DN
     */
    public static String test;
    public DN() {
        initComponents();
        txttaikhoan.setBorder(red_bottom_border);
        txtmatkhau.setBorder(red_bottom_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btdangnhap = new javax.swing.JButton();
        txtmatkhau = new javax.swing.JPasswordField();
        txttaikhoan = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lbdmk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG NHẬP");

        btdangnhap.setBackground(new java.awt.Color(247, 202, 24));
        btdangnhap.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btdangnhap.setForeground(new java.awt.Color(255, 255, 255));
        btdangnhap.setText("Đăng nhập");
        btdangnhap.setToolTipText("");
        btdangnhap.setBorder(null);
        btdangnhap.setBorderPainted(false);
        btdangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdangnhapActionPerformed(evt);
            }
        });

        txtmatkhau.setText("password");
        txtmatkhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmatkhauFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmatkhauFocusLost(evt);
            }
        });

        txttaikhoan.setText("Username");
        txttaikhoan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttaikhoanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttaikhoanFocusLost(evt);
            }
        });

        lb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/padlock-24.png"))); // NOI18N

        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/user-24.png"))); // NOI18N
        lb1.setText("   ");

        lbdmk.setText("Đổi mật khẩu?");
        lbdmk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdmkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btdangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txttaikhoan))))
                .addGap(84, 84, 84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lbdmk))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb2))
                .addGap(50, 50, 50)
                .addComponent(btdangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbdmk)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btdangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdangnhapActionPerformed
        // TODO add your handling code here:
        //
        test = txttaikhoan.getText();
        
        //Đăng nhập
        String taikhoan = txttaikhoan.getText();
        String matkhau = txtmatkhau.getText();
        String chucvu1 = "Quản Lý";
        QUANLY ql = new QUANLY();
        QLHDTT1 qlhd = new QLHDTT1();
        try{
            String sql = "select * from nhanvien where taikhoan = '"+taikhoan+"' and matkhau = '"+matkhau+"'";
            ConnectDB cn = new ConnectDB();
            cn.getCn();
            ResultSet rs = cn.executeQuery(sql);
            rs.next();
            String chucvu = rs.getString("chucvu");
            if(chucvu1.equals(chucvu) == true){
                dispose();
                ql.show();  
            }
            else{
                dispose();
                qlhd.show();
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btdangnhapActionPerformed

    private void lbdmkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdmkMouseClicked
        // TODO add your handling code here:
        Doimk dmk = new Doimk();
        dispose();
        dmk.show();
    }//GEN-LAST:event_lbdmkMouseClicked

    private void txttaikhoanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttaikhoanFocusGained
        // TODO add your handling code here:
        if(txttaikhoan.getText().equals("Username")){
            txttaikhoan.setText("");
            
        }
    }//GEN-LAST:event_txttaikhoanFocusGained

    private void txttaikhoanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttaikhoanFocusLost
        // TODO add your handling code here:
        if(txttaikhoan.getText().equals("")){
            txttaikhoan.setText("Username");
            
        }
    }//GEN-LAST:event_txttaikhoanFocusLost

    private void txtmatkhauFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmatkhauFocusGained
        // TODO add your handling code here:
        if(txtmatkhau.getText().equals("password")){
            txtmatkhau.setText("");
            
        }
        
    }//GEN-LAST:event_txtmatkhauFocusGained

    private void txtmatkhauFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmatkhauFocusLost
        // TODO add your handling code here:
        if(txtmatkhau.getText().equals("")){
            txtmatkhau.setText("password");
            
        }
    }//GEN-LAST:event_txtmatkhauFocusLost

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbdmk;
    private javax.swing.JPasswordField txtmatkhau;
    private javax.swing.JTextField txttaikhoan;
    // End of variables declaration//GEN-END:variables
}
