/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.*;
import POJO.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.List;
import java.time.LocalDate;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TIMOON
 */
public class QLHDTT1 extends javax.swing.JFrame {

    Vector data = new Vector();
    Vector title = new Vector();
    Vector data1 = new Vector();
    Vector title1 = new Vector();
    public ArrayList<Ban> dsban = BANDAO.getDSB();
    public ArrayList<Sanpham> dssp = SP1DAO.getDSSP();
    public ArrayList<QLHDTTPJ> dscthd = QLHDTTDAO.getDSQLHDTT();
    public ArrayList<POJO.NHANVIEN> dsnv = NVDAO.getDSNV();
    public ArrayList<Hoadon> dshd = HDDAO.getDSHD();
    public ArrayList<Chitiethoadon> dscthd1 = CTHDDAO.getDSCTHD();
    /**
     * Creates new form QLHDTT
     */
    public QLHDTT1() {
        initComponents();
        //
        
//        lbten.setText(tennv);
        showData5();
        txttongtien.setEditable(false);
        
        
        
        setBackground(new Color(0,0,0));
        tbban.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,12));
        tbban.getTableHeader().setOpaque(true);
        tbban.getTableHeader().setBackground(new Color(32,136,203));
        tbban.getTableHeader().setForeground(new Color(255,255,255));
        tbban.setRowHeight(25);
        //
//        int row = tbban.getSelectedRow();
//        String maban = tbban.getValueAt(row, 0).toString().trim();
//        data.removeAllElements();
//        showData4(maban);
//        showData();
        //Ban
        title.add("Mã bàn");
        title.add("Tên bàn");
        title.add("Trạng thái");
        showData();
        showData2();
        showData3();
        //SPORDER
        title1.add("Tên sản phẩm");
        title1.add("Số lượng");
        title1.add("Giá tiền/sp");
        title1.add("Đơn vị tính");
        
    }

    public void showData(){
        dsban = BANDAO.getDSB();
        data.removeAllElements();
        for(Ban b : dsban){
            Vector v = new Vector();
            v.add(b.getMaban()); v.add(b.getTenban()); v.add(b.getTrangthai());
            data.add(v);
        }
        tbban.setModel(new DefaultTableModel(data, title));
    }
    
    
    public void showData2(){
        for(Sanpham sp: dssp){
            cborder.addItem(sp.getTensp());
        }
    }
    
    public void showData3(){
        for(Ban b: dsban){
            cbchuyenban.addItem(b.getTenban());
        }
    }
    
    public void showData5(){
        String taikhoan = DN.test;
        dsnv = NVDAO.HienthiNV(taikhoan);
        for(POJO.NHANVIEN b: dsnv){
            this.lbten.setText(b.getTennv());
            this.lbmanv.setText(b.getManv());
        }
    }
    
    public void showData4(String maban)
    {
        
        dscthd = QLHDTTDAO.HienthiDLHD(maban);
        data1.removeAllElements();
        for(QLHDTTPJ a : dscthd){
            Vector v = new Vector();
            v.add(a.getTensp());
            v.add(a.getSoluong());
            v.add(a.getGiatien());
            v.add(a.getDvt());
            data1.add(v);
        }
        
        tborder.setModel(new DefaultTableModel(data1,title1));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cborder = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        btthemnuoc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tborder = new javax.swing.JTable();
        btchuyenban = new javax.swing.JButton();
        cbchuyenban = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txttongtien = new javax.swing.JTextField();
        btthanhtoan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbtenban = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbmahd = new javax.swing.JLabel();
        lbmanv = new javax.swing.JLabel();
        lbten = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbban = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("hicoffee");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HI COFFEE");

        jLabel2.setBackground(new java.awt.Color(247, 202, 24));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐĂNG XUẤT");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(247, 202, 24));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CÁ NHÂN");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(394, 394, 394)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("DANH SÁCH BÀN:");

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.add(cborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Order:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 50, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Số lượng:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        txtsoluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsoluongKeyTyped(evt);
            }
        });
        jPanel3.add(txtsoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 140, -1));

        btthemnuoc.setText("Thêm nước");
        btthemnuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btthemnuocMouseClicked(evt);
            }
        });
        btthemnuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemnuocActionPerformed(evt);
            }
        });
        jPanel3.add(btthemnuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        tborder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tborder);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 140));

        btchuyenban.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btchuyenban.setText("Chuyển Bàn");
        btchuyenban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchuyenbanActionPerformed(evt);
            }
        });
        jPanel3.add(btchuyenban, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jPanel3.add(cbchuyenban, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tổng tiền:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));
        jPanel3.add(txttongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 170, -1));

        btthanhtoan.setText("THANH TOÁN");
        btthanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthanhtoanActionPerformed(evt);
            }
        });
        jPanel3.add(btthanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 110, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tên Bàn:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        jPanel3.add(lbtenban, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/engraved-coffee-shop-related-objects-background_281653-1170.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 630, -1));
        jPanel3.add(lbmahd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 110, 20));
        jPanel3.add(lbmanv, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 70, 20));

        lbten.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        tbban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbban);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbten, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap(963, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbten, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btthemnuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemnuocActionPerformed
        // TODO add your handling code here:
        int row = tbban.getSelectedRow();
        String maban = tbban.getValueAt(row, 0).toString().trim();
        String tenban = tbban.getValueAt(row, 1).toString().trim();
        String trangthai2 = tbban.getValueAt(row, 2).toString().trim();

            String trangthai = "Còn trống";
            Ban b = new Ban(maban, tenban, trangthai2);
                
                String sql = "select count(mahd) from HoaDon";
                ConnectDB cn = new ConnectDB();
                cn.getCn();
                ResultSet rset = cn.executeQuery(sql);
                int soHD=-1;
                try {
                    rset.next();
                    soHD=rset.getInt(1);
                } catch (SQLException ex) {
                }
                cn.close();
                
            if(trangthai.equals(trangthai2) == true){
                
                String mahd = "HD"+(soHD+1);
                String manv = lbmanv.getText();;
                String trangthaihd = "";
                LocalDate now = LocalDate.now();
                String date = now+"";
                int tongtien = 0;          
                Hoadon hd = new Hoadon(mahd,manv,maban,date,tongtien,trangthaihd);
                
                dsban = BANDAO.getDSB();
                data.removeAllElements();
                BANDAO.FixTT(b);
                dshd = HDDAO.getDSHD();
                HDDAO.UpdateSQL(hd);
                showData();
            }
            ////////////////////////////////////////////////////////////////////////
            //ORDER
            //
            String tensp = (String) cborder.getSelectedItem() ;
            //Khai báo:
            String mahd1;
            String masp;
            int soluong;
            int thanhtien;
            //SQL
            //
            String sql1 = "select masp, tensp,giatien from sanpham where tensp= N'"+tensp+"'";
            ConnectDB cn1 = new ConnectDB();
            cn1.getCn();
            ResultSet rset1 = cn1.executeQuery(sql1);
            String masp1 = "";
            int giatien = -1;
                try {
                    rset1.next();
                    masp1 = rset1.getString(1);
                    giatien = rset1.getInt(3);
                    
                } catch (SQLException ex) {
                }
                
            cn1.close();
            
            mahd1 = lbmahd.getText();
            soluong = Integer.parseInt(txtsoluong.getText());
            Chitiethoadon cthd = new Chitiethoadon(mahd1,masp1,soluong,giatien);
            dscthd1 = CTHDDAO.getDSCTHD();
            data1.removeAllElements();
            CTHDDAO.FixTHEMSL(mahd1, masp1, soluong);
            CTHDDAO.UpdateSQL(cthd);
            
            String sql2 = "select sum(thanhtien * soluong) from chitiethoadon where mahd= N'"+mahd1+"'";
            ConnectDB cn2 = new ConnectDB();
            cn2.getCn();
            ResultSet rset2 = cn2.executeQuery(sql2);
            int tongtien = -1;
                try {
                    while(rset2.next()){
                        tongtien = rset2.getInt(1);
                        txttongtien.setText(tongtien+"");
                    }

                } catch (SQLException ex) {
                }
                
            cn2.close();
            showData4(maban);
            
        
    }//GEN-LAST:event_btthemnuocActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        DN dn = new DN();
        dispose();
        dn.show();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tbbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbanMouseClicked
        // TODO add your handling code here:
        int row = tbban.getSelectedRow();
        String maban = tbban.getValueAt(row, 0).toString().trim();
        String trangthai = tbban.getValueAt(row, 2).toString().trim();
        String trangthai1 = "Còn trống";
        String sql = "select Mahd from HoaDon where maban = '"+maban+"' and tinhtrang = N'Chưa thanh toán'";
        ConnectDB cn = new ConnectDB();
        cn.getCn();
        ResultSet rset = cn.executeQuery(sql);
            try {
                
                while (rset.next()) {
                   String mahd = rset.getString("Mahd");
                   lbmahd.setText(mahd);
                }
                
            } catch (SQLException ex) {
            }
        cn.close();
        showData4(maban);
        
        String mahd1;
        mahd1 = lbmahd.getText();
        if(trangthai1.equals(trangthai) == false){
        String sql2 = "select sum(thanhtien * soluong) from chitiethoadon where mahd= N'"+mahd1+"'";
            ConnectDB cn2 = new ConnectDB();
            cn2.getCn();
            ResultSet rset2 = cn2.executeQuery(sql2);
            int tongtien = 0;
                try {
                    while(rset2.next()){
                        tongtien = rset2.getInt(1);
                        txttongtien.setText(tongtien+"");
                    }

                } catch (SQLException ex) {
                }
                
            cn2.close();
        }
        else{
            txttongtien.setText("0");
        }
        

    }//GEN-LAST:event_tbbanMouseClicked

    private void btthemnuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btthemnuocMouseClicked
        // TODO add your handling code here:
            
            
    }//GEN-LAST:event_btthemnuocMouseClicked

    private void btchuyenbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchuyenbanActionPerformed
        // TODO add your handling code here:
        int row = tbban.getSelectedRow();
        String bandoi = cbchuyenban.getSelectedItem().toString();
        String mahd = lbmahd.getText();
        String maban = tbban.getValueAt(row, 0).toString().trim();

        
        String sql = "select maban,trangthai from ban where tenban like '%"+bandoi+"%'";
                ConnectDB cn = new ConnectDB();
                cn.getCn();
                ResultSet rset = cn.executeQuery(sql);
                String maban1 = "";
                String trangthai = "";
                try {
                    rset.next();
                    maban1 = rset.getString("maban");
                    trangthai = rset.getString("trangthai");
                    
                } catch (SQLException ex) {
                }
                cn.close();
        
       
            BANDAO.FixTTTWO(maban);
            BANDAO.FixTTTHREE(maban1);
            HDDAO1.CHUYENBAN(mahd, maban1);

            showData4(maban);
            showData();
        
        
        
    }//GEN-LAST:event_btchuyenbanActionPerformed

    private void btthanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthanhtoanActionPerformed
        // TODO add your handling code here:
        int row = tbban.getSelectedRow();
        String maban = tbban.getValueAt(row, 0).toString().trim();
        int tongtien = Integer.parseInt(txttongtien.getText());
        String mahd = lbmahd.getText();
        HDDAO1.THANHTOAN(tongtien, mahd);
        BANDAO.FixTTTWO(maban);
        showData4(maban);
        showData();
    }//GEN-LAST:event_btthanhtoanActionPerformed

    private void txtsoluongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsoluongKeyTyped
        // TODO add your handling code here:
        char t = evt.getKeyChar();
        if(t < '0' || t > '9')
            evt.consume();
    }//GEN-LAST:event_txtsoluongKeyTyped

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        NHANVIEN1 nv = new NHANVIEN1();
        dispose();
        nv.show();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHDTT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHDTT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHDTT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHDTT1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QLHDTT1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btchuyenban;
    private javax.swing.JButton btthanhtoan;
    private javax.swing.JButton btthemnuoc;
    private javax.swing.JComboBox<String> cbchuyenban;
    private javax.swing.JComboBox<String> cborder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbmahd;
    private javax.swing.JLabel lbmanv;
    private javax.swing.JLabel lbten;
    private javax.swing.JLabel lbtenban;
    private javax.swing.JTable tbban;
    private javax.swing.JTable tborder;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables
}
